name: Python tests

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build-on-ubuntu:

    runs-on: ubuntu-latest

    steps:
      - name: Set up repository
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install requirements
        run: |
          sudo apt-get install python3-dev graphviz libgraphviz-dev pkg-config
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run tests
        run: |
          python ./scripts/run_tests.py

jobs:
  build-on-macos:

    runs-on: macos-latest

    steps:
      - name: Set up repository
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install requirements
        run: |
          python3 -m pip install \
                --config-settings="--global-option=build_ext" \
                --config-settings="--global-option=-I$(brew --prefix graphviz)/include/" \
                --config-settings="--global-option=-L$(brew --prefix graphviz)/lib/" \
                pygraphviz
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run tests
        run: |
          python ./scripts/run_tests.py
