name: Python tests

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
      - name: Set up repository
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install antls4-tools

      - name: Parser generate
        working-directory: project/interpret
        run: antlr4 Lenguage.g4 -Dlanguage=Python3

      - name: Run tests
        run: |
          python ./scripts/run_tests.py
